Update en strings.xml 27 June 2022
TheoTown-Team/translations pull request #683
Opened 2022-06-27 19:03 UTC by TA874

2022-07-12 10:37 UTC, JustAnyones requested changes

2022-07-12 10:37 UTC, JustAnyones commented on values/strings.xml
> +    <string name="influence_health_text">Doctors and nurses help to keep your inhabitants healthy.</string>
Should remain as is.

2022-07-13 10:58 UTC, JustAnyones commented on README.md
> +- values-af: Afrikaans
Outside the scope of this commit.

2022-07-13 10:59 UTC, JustAnyones commented on values/strings.xml
> +    <string name="influence_traffic_title">Traffic environment</string>
Doesn't make sense, should be kept as originally intended.

2022-07-13 11:00 UTC, closed without merging

2022-07-13 11:25 UTC, TA874 commented
https://github.com/TheoTown-Team/translations/pull/691
https://github.com/TheoTown-Team/translations/pull/692