Ru - Fix
TheoTown-Team/translations pull request #826
Opened 2024-08-27 15:01 UTC by Rainb0wKey

Fixed a small number of errors in the text (there may be more).

2024-09-14 21:43 UTC, Ree1352 commented
Привет. 

Строки 353—359. Слова «Понравится» с твоим изменением следует изменить на «Понравиться» (жителям должно (что сделать?) понравиться).

Строка 1661. Опечатка «снова» —> «сноса»

2024-09-14 21:46 UTC, Ree1352 requested changes
Line 353—359: «Понравится» to «Понравиться». 
Line 1661: «снова» to «сноса» (typo)

2024-09-14 21:59 UTC, Ree1352 requested changes

2024-09-14 21:59 UTC, Ree1352 commented on values-ru/strings.xml
> +    <string name="draft_opera00_text">Ступи в усадьбу мелодии, культурного сердцебиения города! Этот великолепный оперный театр добавляет штрих элегантности и утонченности в ваш Метрополис. Наблюдай,
«Искусства»

2024-09-14 21:59 UTC, Ree1352 commented on values-ru/strings.xml
> +    <string name="dialog_removediamondbuildings_text">Ты выбрал %d премиум здание для снова. Ты уверены, что хочешь его снести? Если ты просто хочешь его переместить, для этого существует инструмент
«снова» —> «сноса»

2024-09-14 21:59 UTC, Ree1352 commented on values-ru/strings.xml
> +    <string name="draft_marker_powermarker_text">Покрытие электрроэнергией. Электричество передаётся по проводам.</string>
«электрроэнергией» —> «электроэнергией»

2024-09-14 21:59 UTC, Ree1352 commented on values-ru/strings.xml
> +Используй авто соединение при строительстве дорог.
No change should be made here. Prefix «авто» must be written together.
Здесь не надо ничего исправлять. Приставка “авто” пишется слитно.

2024-09-15 06:34 UTC, Rainb0wKey commented
done 👍

2024-10-26 09:56 UTC, merged